---
title: "Eda_Final_Geo_Peter"
author: "Zhengqi Tian"
date: "11/18/2021"
output: github_document
---


```{r}
library(ggdemetra)
library(tidyverse)
library(ggplot2)
library(ggpubr)
```

```{r}
data <- read_csv("Energy Census and Economic Data US 2010-2014.csv")
```

```{r}
head(data)
```
```{r}
#remove NA
data=na.omit(data)
```
# Geo Analysis-EDA
```{r}
#Filter data for GeoC
GeoC<-data%>%
  select("StateCodes","State","Region","Division","Coast",`Great Lakes`,"GeoC2010","GeoC2011","GeoC2012","GeoC2013","GeoC2014")%>%
  pivot_longer(c("GeoC2010","GeoC2011","GeoC2012","GeoC2013","GeoC2014"), names_to = "Year", values_to = "GeoConsumption")
#Clean Year GeoC
GeoC$Year<-gsub("GeoC","",as.character(GeoC$Year))
#Display the outcome
GeoC

#Filter data for GeoP
GeoP<-data%>%
  select("StateCodes","GeoP2010","GeoP2011","GeoP2012","GeoP2013","GeoP2014")%>%
  pivot_longer(c("GeoP2010","GeoP2011","GeoP2012","GeoP2013","GeoP2014"), names_to = "Year", values_to = "GeoProduction")
#Clean Year GeoP
GeoP$Year<-gsub("GeoP","",as.character(GeoP$Year))
#Display the outcome
GeoP

```




```{r}
#Add cumlative column
#Join four Tables into one
Geo<-left_join(GeoC,GeoP,by=c('StateCodes','Year'))

Geo<-Geo%>%
  mutate(CumGeoConsumption=cumsum(GeoConsumption))%>%
  mutate(CumGeoProduction=cumsum(GeoProduction))
Geo
```

# Geo Consumption Visulization
```{r}
#Rank top 5 state of Geo Consumption each year. (Bar plot)
#Overall
GeoCgeneral<-ggplot(data=Geo,aes(y=GeoConsumption,x=reorder(State,GeoConsumption)))+geom_col(aes(fill=State))+
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+
  labs(
    title="2011 to 2014",
    x="State",
    y="Cunsumption"
  )+
  theme(legend.position = 'none')+
  theme(plot.title = element_text(hjust = 0.5))
GeoCgeneral+facet_grid(Year ~.)

#Top 5 States in GeoC2010
GeoC2010<-Geo%>%
  filter(Year==2010)%>%
  arrange(desc(GeoConsumption))%>%
  slice(1:5)%>%
  ggplot(aes(x=reorder(State,GeoConsumption),y=GeoConsumption))+geom_col(aes(fill=State))+
  labs(
    title="2010",
    x="State",
    y="Cunsumption"
  )+
  theme(legend.position = 'none')+
  theme(plot.title = element_text(hjust = 0.5))+
  coord_flip()
GeoC2010

#Top 5 States in Geo2011
GeoC2011<-Geo%>%
  filter(Year==2011)%>%
  arrange(desc(GeoConsumption))%>%
  slice(1:5)%>%
  ggplot(aes(x=reorder(State,GeoConsumption),y=GeoConsumption))+geom_col(aes(fill=State))+
  labs(
    title="2011",
    x="State",
    y="Cunsumption"
  )+
  theme(legend.position = 'none')+
  coord_flip()+
  theme(plot.title = element_text(hjust = 0.5)) 
GeoC2011

#Top 5 States in Geo2012
GeoC2012<-Geo%>%
  filter(Year==2012)%>%
  arrange(desc(GeoConsumption))%>%
  slice(1:5)%>%
  ggplot(aes(x=reorder(State,GeoConsumption),y=GeoConsumption))+geom_col(aes(fill=State))+
  labs(
    title="2012",
    x="State",
    y="Cunsumption"
  )+
  theme(legend.position = 'none')+
  coord_flip()+
  theme(plot.title = element_text(hjust = 0.5)) 
GeoC2012
#Top 5 Sates in Geo2013
GeoC2013<-Geo%>%
  filter(Year==2013)%>%
  arrange(desc(GeoConsumption))%>%
  slice(1:5)%>%
  ggplot(aes(x=reorder(State,GeoConsumption),y=GeoConsumption))+geom_col(aes(fill=State))+
  labs(
    title="2013",
    x="State",
    y="Cunsumption"
  )+
  theme(legend.position = 'none')+
  theme(plot.title = element_text(hjust = 0.5)) +
  coord_flip()
GeoC2013
#Top 5 Sates in Geo2014
GeoC2014<-Geo%>%
  filter(Year==2014)%>%
  arrange(desc(GeoConsumption))%>%
  slice(1:5)%>%
  ggplot(aes(x=reorder(State,GeoConsumption),y=GeoConsumption))+geom_col(aes(fill=State))+
   labs(
    title="2014",
    x="State",
    y="Cunsumption"
  )+
  theme(legend.position = 'none')+
  theme(plot.title = element_text(hjust = 0.5))+
  coord_flip()
GeoC2014
#Combine all together
ggarrange(GeoCgeneral,GeoC2010,GeoC2011,GeoC2012,GeoC2013,GeoC2014,nrow=2,ncol=3)


```

```{r}
#Boxplot to show mean, median, min, max for each energy by coasts annually
# is_outlier that will return a boolean TRUE/FALSE if the value passed to it is an outlier. 
is_outlier <- function(x) {
  return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5* IQR(x))
}


#General
GeoCboxgeneral<-Geo%>%
  mutate(outlier = ifelse(is_outlier(GeoConsumption),State, as.numeric(NA))) %>%
  ggplot(aes(x=Year,y=GeoConsumption,fill=Year))+geom_boxplot(outlier.colour="red", outlier.shape=8, outlier.size=4)+
  labs(
    title="Boxplot for Geo Conumption from 2010 to 2014",
    x="Year",
    y="Consumption",
  )+
  geom_text(aes(label = outlier,color=outlier), na.rm = TRUE, hjust = -0.5)+
  geom_jitter()+
  theme(plot.title = element_text(hjust = 0.5))
GeoCboxgeneral

#2010
GeoCbox2010<-Geo%>%
  filter(Year==2010)%>%
  ggplot(aes(x=factor(Region),y=GeoConsumption,fill=factor(Region)))+geom_violin()+
  labs(
    title="Violin Boxplot for Geo Conumption in 2010 Based on Region",
    x="Region",
    y="Consumption",
  )+
  theme(plot.title = element_text(hjust = 0.5))
GeoCbox2010

#2011
GeoCbox2011<-Geo%>%
  filter(Year==2011)%>%
  ggplot(aes(x=factor(Region),y=GeoConsumption,fill=factor(Region)))+geom_violin()+
  labs(
    title="Violin Boxplot for Geo Conumption in 2011 Based on Region",
    x="Region",
    y="Consumption",
  )+
  theme(plot.title = element_text(hjust = 0.5))
GeoCbox2011
#2012
GeoCbox2012<-Geo%>%
  filter(Year==2012)%>%
  ggplot(aes(x=factor(Region),y=GeoConsumption,fill=factor(Region)))+geom_violin()+
  labs(
    title="Violin Boxplot for Geo Conumption in 2012 Based on Region",
    x="Region",
    y="Consumption",
  )+
  theme(plot.title = element_text(hjust = 0.5))
GeoCbox2012

#2013
GeoCbox2013<-Geo%>%
  filter(Year==2013)%>%
  ggplot(aes(x=factor(Region),y=GeoConsumption,fill=factor(Region)))+geom_violin()+
  labs(
    title="Violin Boxplot for Geo Conumption in 2013 Based on Region",
    x="Region",
    y="Consumption",
  )+
  theme(plot.title = element_text(hjust = 0.5))
GeoCbox2013

#2014
GeoCbox2014<-Geo%>%
  filter(Year==2014)%>%
  ggplot(aes(x=factor(Region),y=GeoConsumption,fill=factor(Region)))+geom_violin()+
  labs(
    title="Violin Boxplot for Geo Conumption in 2014 Based on Region",
    x="Region",
    y="Consumption",
  )+
  theme(plot.title = element_text(hjust = 0.5))
GeoCbox2014

#Combine all together
ggarrange(GeoCboxgeneral,GeoCbox2010,GeoCbox2011,GeoCbox2012,GeoCbox2013,GeoCbox2014,nrow=2,ncol=3)

```

```{r}
#Time series for Geo Consumption
Geo$Year=as.numeric(Geo$Year)
Geo%>%
  filter(StateCodes=="CA"|StateCodes=="FL"|State=="Michigan"|State=="Indiana"|State=="Nevada")%>%
  ggplot(aes(x = Year,y = CumGeoConsumption)) +geom_point(aes(color=factor(State))) +geom_line(aes(color=factor(State))) 

```

```{r}
head(Geo)
```

# Geo Production Visulization
```{r}
#Rank top 5 state of Geo production each year. (Bar plot)
#Overall
GeoPgeneral<-ggplot(data=Geo,aes(y=GeoProduction,x=reorder(State,GeoProduction)))+geom_col(aes(fill=State))+
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+
  labs(
    title="From 2011 to 2014",
    x="State",
    y="GeoProduction"
  )+
  theme(legend.position = 'none')+
  theme(plot.title = element_text(hjust = 0.5))
GeoPgeneral+facet_grid(Year ~.)
#Top 5 city in GeoP2010
GeoP2010<-Geo%>%
  filter(Year==2010)%>%
  arrange(desc(GeoProduction))%>%
  slice(1:5)%>%
  ggplot(aes(x=reorder(State,GeoProduction),y=GeoProduction))+geom_col(aes(fill=State))+
  labs(
    title="2010",
    x="State",
    y="Geo Production"
  )+
  theme(legend.position = 'none')+
  coord_flip()+
  theme(plot.title = element_text(hjust = 0.5))
GeoP2010

#Top 5 city in Geo2011
GeoP2011<-Geo%>%
  filter(Year==2011)%>%
  arrange(desc(GeoProduction))%>%
  slice(1:5)%>%
  ggplot(aes(x=reorder(State,GeoProduction),y=GeoProduction))+geom_col(aes(fill=State))+
  labs(
    title="2011",
    x="State",
    y="Geo Production"
  )+
  theme(legend.position = 'none')+
  theme(plot.title = element_text(hjust = 0.5))+
  coord_flip()
GeoP2011
#Top 5 city in Geo2012
GeoP2012<-Geo%>%
  filter(Year==2012)%>%
  arrange(desc(GeoProduction))%>%
  slice(1:5)%>%
  ggplot(aes(x=reorder(State,GeoProduction),y=GeoProduction))+geom_col(aes(fill=State))+
  labs(
    title="2012",
    x="State",
    y="Geo Production"
  )+
  theme(legend.position = 'none')+
  theme(plot.title = element_text(hjust = 0.5))+
  coord_flip()
GeoP2012
#Top 5 city in Geo2013
GeoP2013<-Geo%>%
  filter(Year==2013)%>%
  arrange(desc(GeoProduction))%>%
  slice(1:5)%>%
  ggplot(aes(x=reorder(State,GeoProduction),y=GeoProduction))+geom_col(aes(fill=State))+
  labs(
    title="2013",
    x="State",
    y="Geo Production"
  )+
  theme(legend.position = 'none')+
  theme(plot.title = element_text(hjust = 0.5))+
  coord_flip()
GeoP2013
#Top 5 city in Geo2014
GeoP2014<-Geo%>%
  filter(Year==2014)%>%
  arrange(desc(GeoProduction))%>%
  slice(1:5)%>%
  ggplot(aes(x=reorder(State,GeoProduction),y=GeoProduction))+geom_col(aes(fill=State))+
  labs(
    title="2014",
    x="State",
    y="Geo Production"
  )+
  theme(legend.position = 'none')+
  theme(plot.title = element_text(hjust = 0.5))+
  coord_flip()
GeoP2014
#Combine all together
ggarrange(GeoPgeneral,GeoP2010,GeoP2011,GeoP2012,GeoP2013,GeoP2014,nrow=2,ncol=3)
```

```{r}
#Boxplot to show mean, median, min, max for each energy by coasts annually
Geo$Year=as.character(Geo$Year)
# is_outlier that will return a boolean TRUE/FALSE if the value passed to it is an outlier. 
is_outlier <- function(x) {
  return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5* IQR(x))
}
#General
GeoPboxgeneral<-Geo%>%
  mutate(outlier = ifelse(is_outlier(GeoProduction),State, as.numeric(NA))) %>%
  ggplot(aes(x=Year,y=GeoProduction,fill=Year))+geom_boxplot(outlier.colour="red", outlier.shape=8, outlier.size=4) + 
  geom_jitter()+
  labs(
    title="Boxplot for Geo Production from 2010 to 2014",
    x="Year",
    y="Production",
  )+
  geom_text(aes(label = outlier,color=outlier), na.rm = TRUE, hjust = 0.1)+
  theme(plot.title = element_text(hjust = 0.5))
  
GeoPboxgeneral

#2010
GeoPbox2010<-Geo%>%
  filter(Year==2010)%>%
  ggplot(aes(x=factor(Region),y=GeoProduction,fill=factor(Region)))+geom_violin()+
  labs(
    title="Violin Boxplot for Geo Production in 2010 Based on Region",
    x="Region",
    y="Production",
  )+
  theme(plot.title = element_text(hjust = 0.5))

GeoPbox2010

#2011
GeoPbox2011<-Geo%>%
  filter(Year==2010)%>%
  ggplot(aes(x=factor(Region),y=GeoProduction,fill=factor(Region)))+geom_violin()+
  labs(
    title="Violin Boxplot for Geo Production in 2011 Based on Region",
    x="Region",
    y="Production",
  )+
  theme(plot.title = element_text(hjust = 0.5))
GeoPbox2011
#2012
GeoPbox2012<-Geo%>%
  filter(Year==2010)%>%
  ggplot(aes(x=factor(Region),y=GeoProduction,fill=factor(Region)))+geom_violin()+
  labs(
    title="Violin Boxplot for Geo Production in 2012 Based on Region",
    x="Region",
    y="Consumption",
  )+
  theme(plot.title = element_text(hjust = 0.5))
GeoPbox2012

#2013
GeoPbox2013<-Geo%>%
  filter(Year==2010)%>%
  ggplot(aes(x=factor(Region),y=GeoProduction,fill=factor(Region)))+geom_violin()+
  labs(
    title="Violin Boxplot for Geo Production in 2013 Based on Region",
    x="Region",
    y="Production",
  )+
  theme(plot.title = element_text(hjust = 0.5))
GeoPbox2013

#2014
GeoPbox2014<-Geo%>%
  filter(Year==2010)%>%
  ggplot(aes(x=factor(Region),y=GeoProduction,fill=factor(Region)))+geom_violin()+
  labs(
    title="Violin Boxplot for Geo Production in 2014 Based on Region",
    x="Region",
    y="Production",
  )+
  theme(plot.title = element_text(hjust = 0.5))
GeoPbox2014

#Combine all together
ggarrange(GeoPboxgeneral,GeoPbox2010,GeoPbox2011,GeoPbox2012,GeoPbox2013,GeoPbox2014,nrow=2,ncol=3)

```



```{r}
#Time series for Geo Production
Geo$Year=as.numeric(Geo$Year)
ggplot(Geo,aes(x = Year,y = CumGeoProduction)) +geom_point(aes(color=factor(State))) +geom_line(aes(color=factor(State))) 

```